### ISSUE TITLE
Device with serial number '$validserial' is not a door.

### ISSUE THREAD

**Issue by TheseArmsRSnakes** [thomasmunduchira/myq-api#24]
Hello, 

I'd like to interface with a MYQ-G0301. Call attempts result in ERR_MYQ_INVALID_DEVICE. The serial is correct -- in that it is identical to what's displayed in the myq smart phone application. Have I encountered a bug or am I trying to use the API for an unsupported device? 

Happy to provide serial if needed. 

```
MyQError: Device with serial number '$validserial' is not a door.
    at MyQ.getDoorState (/Users/$user/Git/myq-alexa/node_modules/myq-api/src/MyQ.js:245:15)
    at processTicksAndRejections (<node_internals>/internal/process/task_queues.js:93:5)
    at async doorStatus (/Users/$user/Git/myq-alexa/index.js:17:22)
    at async Object.handle (/Users/$user/Git/myq-alexa/index.js:106:40) {name: 'MyQError', code: 'ERR_MYQ_INVALID_DEVICE', stack: 'MyQError: Device with serial number 'GW230000…Users/$user/Git/myq-alexa/index.js:106:40)', message: 'Device with serial number '$validserial'' is not a door.'}
index.js:20

code:'ERR_MYQ_INVALID_DEVICE'
message:'Device with serial number '$validserial' is not a door.'
name:'MyQError'
stack:'MyQError: Device with serial number '$validserial' is not a door.\n    at MyQ.getDoorState (/Users/$user/Git/myq-alexa/node_modules/myq-api/src/MyQ.js:245:15)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async doorStatus (/Users/$user/Git/myq-alexa/index.js:17:22)\n    at async Object.handle (/Users/$user/Git/myq-alexa/index.js:106:40)'
__proto__:Error
constructor:class MyQError extends Error {\n  /**\n   * Construct an error to be returned by the myQ API.\n   *\n   * @param {string} message Error message\n   * @param {string} code Error code\n   * @param {object} _serviceError Optional raw service error\n   */\n  constructor(message, code, _serviceError) {\n    super(message);\n    this.name = this.constructor.name;\n    this.code = code;\n    if (_serviceError !== undefined) {\n      this._serviceError = _serviceError;\n    }\n  }\n}
```

**Comment by thomasmunduchira** [comment]
Hi there @TheseArmsRSnakes,

The MYQ-G0301 is the model number for the [myQ Smart Garage Hub](https://www.chamberlain.com/myq-smart-garage-hub/p/MYQ-G0301-E). You want to be calling this API with the serial number of your garage door, not the hub. myQ treats these as separate devices.

I suggest you call [getDevices()](https://github.com/thomasmunduchira/myq-api#getdevices) via this API to get all the devices on your account. Find the device that has the `device_family` field set to "garagedoor" - that is the device you're looking for. Try seeing if the associated serial number for that device does the trick.

**Comment by TheseArmsRSnakes** [comment]
Thank you @thomasmunduchira. Works!
